Repository SwiftGen/SwiftGen, pull requests merged in 2018-09, with the labels that each got.

#480 XCAssets: disable allValues by default
  CHANGELOG.md
  Documentation/templates/MigrationGuide.md
  Documentation/templates/xcassets/swift3.md
  Documentation/templates/xcassets/swift4.md
  Tests/Fixtures/Generated/XCAssets/swift3-context-all-allValues.swift
  Tests/Fixtures/Generated/XCAssets/swift3-context-all-customname.swift
  Tests/Fixtures/Generated/XCAssets/swift3-context-all-forceNamespaces.swift
  Tests/Fixtures/Generated/XCAssets/swift3-context-all-publicAccess.swift
  Tests/Fixtures/Generated/XCAssets/swift3-context-all.swift
  Tests/Fixtures/Generated/XCAssets/swift4-context-all-allValues.swift
  Tests/Fixtures/Generated/XCAssets/swift4-context-all-customname.swift
  Tests/Fixtures/Generated/XCAssets/swift4-context-all-forceNamespaces.swift
  Tests/Fixtures/Generated/XCAssets/swift4-context-all-publicAccess.swift
  Tests/Fixtures/Generated/XCAssets/swift4-context-all.swift
  Tests/TemplatesTests/XCAssetsTests.swift
  templates/xcassets/swift3.stencil
  templates/xcassets/swift4.stencil
Labels: change: breaking

#482 XCAssets: remove deprecated constants and types.
  CHANGELOG.md
  Documentation/SwiftGenKit Contexts/Assets.md
  Documentation/templates/MigrationGuide.md
  Documentation/templates/xcassets/swift3.md
  Documentation/templates/xcassets/swift4.md
  Sources/SwiftGenKit/Stencil/AssetsCatalogContext.swift
  Tests/Fixtures/Generated/XCAssets/swift3-context-all-allValues.swift
  Tests/Fixtures/Generated/XCAssets/swift3-context-all-customname.swift
  Tests/Fixtures/Generated/XCAssets/swift3-context-all-forceNamespaces.swift
  Tests/Fixtures/Generated/XCAssets/swift3-context-all-publicAccess.swift
  Tests/Fixtures/Generated/XCAssets/swift3-context-all.swift
  Tests/Fixtures/Generated/XCAssets/swift4-context-all-allValues.swift
  Tests/Fixtures/Generated/XCAssets/swift4-context-all-customname.swift
  Tests/Fixtures/Generated/XCAssets/swift4-context-all-forceNamespaces.swift
  Tests/Fixtures/Generated/XCAssets/swift4-context-all-publicAccess.swift
  Tests/Fixtures/Generated/XCAssets/swift4-context-all.swift
  templates/xcassets/swift3.stencil
  templates/xcassets/swift4.stencil
Labels: change: breaking

#502 Strings: fix format parser to handle `% d` and `%#x`
  CHANGELOG.md
  Sources/SwiftGenKit/Parsers/Strings/PlaceholderType.swift
  Tests/SwiftGenKitTests/StringParserTests.swift
Labels: type: bug/fix

#506 Fix (completely) broken swiftlint for output
  CHANGELOG.md
  Scripts/SwiftLint.sh
  Scripts/swiftlint_no_disable_all.sh
Labels: type: bug/fix

#484 Migration Guide for SwiftGen 6.0
  CHANGELOG.md
  Documentation/Creating-your-templates.md
  Documentation/MigrationGuide.md
  Documentation/SwiftGenKit Contexts/MigrationGuide.md
  Documentation/templates/MigrationGuide.md
  Documentation/templates/colors/literals-swift3.md
  Documentation/templates/colors/literals-swift4.md
  Documentation/templates/colors/swift3.md
  Documentation/templates/colors/swift4.md
  Documentation/templates/fonts/swift3.md
  Documentation/templates/fonts/swift4.md
  Documentation/templates/ib/scenes-swift3.md
  Documentation/templates/ib/scenes-swift4.md
  Documentation/templates/ib/segues-swift3.md
  Documentation/templates/ib/segues-swift4.md
  Documentation/templates/json/inline-swift3.md
  Documentation/templates/json/inline-swift4.md
  Documentation/templates/json/runtime-swift3.md
  Documentation/templates/json/runtime-swift4.md
  Documentation/templates/plist/inline-swift3.md
  Documentation/templates/plist/inline-swift4.md
  Documentation/templates/plist/runtime-swift3.md
  Documentation/templates/plist/runtime-swift4.md
  Documentation/templates/strings/flat-swift3.md
  Documentation/templates/strings/flat-swift4.md
  Documentation/templates/strings/structured-swift3.md
  Documentation/templates/strings/structured-swift4.md
  Documentation/templates/xcassets/swift3.md
  Documentation/templates/xcassets/swift4.md
  Documentation/templates/yaml/inline-swift3.md
  Documentation/templates/yaml/inline-swift4.md
  README.md
Labels: type: documentation

#508 Update building instructions in README
  README.md
Labels: type: documentation

#523 Fix 404 link
  README.md
Labels: type: documentation

#524 Fix typos in README + Improve Dangerfile
  CHANGELOG.md
  CONTRIBUTING.md
  Dangerfile
  README.md
Labels: type: documentation
