Repository SwiftGen/SwiftGen, pull requests merged in 2018-04, with the labels that each got.

#403 Migrate to CircleCI 2.0
  .circleci/config.yml
  .ruby-version
  CHANGELOG.md
  Gemfile.lock
  circle.yml
Labels: type: internal

#402 Enable extra SwiftLint rules
  .swiftlint.yml
  CHANGELOG.md
  Sources/SwiftGen/Commander/ConfigCommands.swift
  Sources/SwiftGen/Commander/OutputDestination.swift
  Sources/SwiftGen/Commander/ParserCLICommands.swift
  Sources/SwiftGen/Commander/TemplatesCommands.swift
  Sources/SwiftGen/Config/Config.swift
  Sources/SwiftGen/Config/ConfigEntry.swift
  Sources/SwiftGen/Path+AppSupport.swift
  Sources/SwiftGen/TemplateRef.swift
  Sources/SwiftGen/main.swift
  Sources/SwiftGenKit/Parsers/ColorsParser.swift
  Sources/SwiftGenKit/Parsers/FontsParser.swift
  Sources/SwiftGenKit/Parsers/StoryboardParser.swift
  Sources/SwiftGenKit/Parsers/StringsParser.swift
  Sources/SwiftGenKit/Stencil/AssetsCatalogContext.swift
  Sources/SwiftGenKit/Stencil/ColorsContext.swift
  Sources/SwiftGenKit/Stencil/StoryboardsContext.swift
  Sources/SwiftGenKit/Stencil/StringsContext.swift
  Tests/SwiftGenKitTests/AssetCatalogTests.swift
  Tests/SwiftGenKitTests/ColorsCLRFileTests.swift
  Tests/SwiftGenKitTests/ColorsJSONFileTests.swift
  Tests/SwiftGenKitTests/ColorsTests.swift
  Tests/SwiftGenKitTests/ColorsTextFileTests.swift
  Tests/SwiftGenKitTests/ColorsXMLFileTests.swift
  Tests/SwiftGenKitTests/FontsTests.swift
  Tests/SwiftGenKitTests/StoryboardsMacOSTests.swift
  Tests/SwiftGenKitTests/StoryboardsiOSTests.swift
  Tests/SwiftGenKitTests/StringParserTests.swift
  Tests/SwiftGenKitTests/StringsTests.swift
  Tests/SwiftGenKitTests/TestsHelper.swift
  Tests/SwiftGenTests/ConfigLintTests.swift
  Tests/SwiftGenTests/ConfigReadTests.swift
  Tests/SwiftGenTests/TestsHelper.swift
  Tests/TemplatesTests/TestsHelper.swift
Labels: type: internal

#398 Stop manipulating strings
  .ruby-version
  CHANGELOG.md
  Sources/SwiftGen/Config/Config.swift
  Sources/SwiftGen/Config/ConfigEntry.swift
  Sources/SwiftGen/Logs.swift
  Sources/SwiftGenKit/Parsers/FontsParser.swift
  Sources/SwiftGenKit/Parsers/StringsParser.swift
  Sources/SwiftGenKit/Stencil/StringsContext.swift
  SwiftGen.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Tests/Fixtures/Generated/Strings/flat-swift2-context-localizable-customname.swift
  Tests/Fixtures/Generated/Strings/flat-swift2-context-localizable-no-comments.swift
  Tests/Fixtures/Generated/Strings/flat-swift2-context-localizable-publicAccess.swift
  Tests/Fixtures/Generated/Strings/flat-swift2-context-localizable.swift
  Tests/Fixtures/Generated/Strings/flat-swift2-context-multiple.swift
  Tests/Fixtures/Generated/Strings/flat-swift3-context-localizable-customname.swift
  Tests/Fixtures/Generated/Strings/flat-swift3-context-localizable-no-comments.swift
  Tests/Fixtures/Generated/Strings/flat-swift3-context-localizable-publicAccess.swift
  Tests/Fixtures/Generated/Strings/flat-swift3-context-localizable.swift
  Tests/Fixtures/Generated/Strings/flat-swift3-context-multiple.swift
  Tests/Fixtures/Generated/Strings/flat-swift4-context-localizable-customname.swift
  Tests/Fixtures/Generated/Strings/flat-swift4-context-localizable-no-comments.swift
  Tests/Fixtures/Generated/Strings/flat-swift4-context-localizable-publicAccess.swift
  Tests/Fixtures/Generated/Strings/flat-swift4-context-localizable.swift
  Tests/Fixtures/Generated/Strings/flat-swift4-context-multiple.swift
  Tests/Fixtures/Generated/Strings/structured-swift2-context-localizable-customname.swift
  Tests/Fixtures/Generated/Strings/structured-swift2-context-localizable-no-comments.swift
  Tests/Fixtures/Generated/Strings/structured-swift2-context-localizable-publicAccess.swift
  Tests/Fixtures/Generated/Strings/structured-swift2-context-localizable.swift
  Tests/Fixtures/Generated/Strings/structured-swift2-context-multiple.swift
  Tests/Fixtures/Generated/Strings/structured-swift3-context-localizable-customname.swift
  Tests/Fixtures/Generated/Strings/structured-swift3-context-localizable-no-comments.swift
  Tests/Fixtures/Generated/Strings/structured-swift3-context-localizable-publicAccess.swift
  Tests/Fixtures/Generated/Strings/structured-swift3-context-localizable.swift
  Tests/Fixtures/Generated/Strings/structured-swift3-context-multiple.swift
  Tests/Fixtures/Generated/Strings/structured-swift4-context-localizable-customname.swift
  Tests/Fixtures/Generated/Strings/structured-swift4-context-localizable-no-comments.swift
  Tests/Fixtures/Generated/Strings/structured-swift4-context-localizable-publicAccess.swift
  Tests/Fixtures/Generated/Strings/structured-swift4-context-localizable.swift
  Tests/Fixtures/Generated/Strings/structured-swift4-context-multiple.swift
  Tests/Fixtures/Resources/Strings/LocStructuredOnly.strings
  Tests/Fixtures/Resources/Strings/LocUTF8.strings
  Tests/Fixtures/Resources/Strings/Localizable.strings
  Tests/Fixtures/StencilContexts/Strings/localizable.plist
  Tests/Fixtures/StencilContexts/Strings/multiple.plist
  Tests/Fixtures/StencilContexts/Strings/structuredonly.plist
  Tests/Fixtures/StencilContexts/Strings/utf8.plist
  Tests/SwiftGenKitTests/TestsHelper.swift
  Tests/SwiftGenTests/ConfigLintTests.swift
  Tests/SwiftGenTests/ConfigReadTests.swift
  Tests/SwiftGenTests/TestsHelper.swift
  Tests/TemplatesTests/TestsHelper.swift
Labels: change: breaking, status: WIP

#415 Update to Xcode 9.3
  .circleci/config.yml
  .ruby-version
  CHANGELOG.md
  Gemfile.lock
  Sources/SwiftGen/Config/Config.swift
  Sources/SwiftGenKit/Parsers/AssetsCatalogParser.swift
  Sources/SwiftGenKit/Parsers/FontsParser.swift
  Sources/SwiftGenKit/Parsers/StoryboardParser.swift
  SwiftGen.xcodeproj/project.pbxproj
  SwiftGen.xcodeproj/xcshareddata/xcschemes/SwiftGenKit - Generate Contexts.xcscheme
  SwiftGen.xcodeproj/xcshareddata/xcschemes/SwiftGenKit.xcscheme
  SwiftGen.xcodeproj/xcshareddata/xcschemes/Templates - Generate Output.xcscheme
  SwiftGen.xcodeproj/xcshareddata/xcschemes/swiftgen.xcscheme
  SwiftGenKit.podspec
Labels: type: internal

#417 Refactor parsers
  CHANGELOG.md
  Sources/SwiftGenKit/Parsers/AssetsCatalogParser.swift
  Sources/SwiftGenKit/Parsers/AssetsCatalogParser/AssetsCatalogParser.swift
  Sources/SwiftGenKit/Parsers/AssetsCatalogParser/Catalog.swift
  Sources/SwiftGenKit/Parsers/AssetsCatalogParser/CatalogEntry.swift
  Sources/SwiftGenKit/Parsers/ColorsParser/ColorsCLRFileParser.swift
  Sources/SwiftGenKit/Parsers/ColorsParser/ColorsFileTypeParser.swift
  Sources/SwiftGenKit/Parsers/ColorsParser/ColorsJSONFileParser.swift
  Sources/SwiftGenKit/Parsers/ColorsParser/ColorsParser.swift
  Sources/SwiftGenKit/Parsers/ColorsParser/ColorsTXTFileParser.swift
  Sources/SwiftGenKit/Parsers/ColorsParser/ColorsXMLFileParser.swift
  Sources/SwiftGenKit/Parsers/FontsParser.swift
  Sources/SwiftGenKit/Parsers/FontsParser/CTFont.swift
  Sources/SwiftGenKit/Parsers/FontsParser/Font.swift
  Sources/SwiftGenKit/Parsers/FontsParser/FontsParser.swift
  Sources/SwiftGenKit/Parsers/StoryboardParser.swift
  Sources/SwiftGenKit/Parsers/StoryboardParser/Storyboard.swift
  Sources/SwiftGenKit/Parsers/StoryboardParser/StoryboardParser.swift
  Sources/SwiftGenKit/Parsers/StoryboardParser/StoryboardPlatform.swift
  Sources/SwiftGenKit/Parsers/StoryboardParser/StoryboardScene.swift
  Sources/SwiftGenKit/Parsers/StoryboardParser/StoryboardSegue.swift
  Sources/SwiftGenKit/Parsers/StringsParser/PlaceholderType.swift
  Sources/SwiftGenKit/Parsers/StringsParser/StringsEntry.swift
  Sources/SwiftGenKit/Parsers/StringsParser/StringsParser.swift
  Sources/SwiftGenKit/Stencil/StoryboardsContext.swift
  Sources/SwiftGenKit/Stencil/StringsContext.swift
  Sources/SwiftGenKit/Utils/Path.swift
  Sources/SwiftGenKit/Utils/String.swift
  SwiftGen.xcodeproj/project.pbxproj
  Tests/SwiftGenKitTests/StringParserTests.swift
Labels: type: internal

#421 Some documentation fixes
  CONTRIBUTING.md
  Documentation/Creating-your-templates.md
  Documentation/MigrationGuide.md
  README.md
Labels: type: documentation
