Repository SwiftGen/SwiftGen, pull requests merged in 2019-02, with the labels that each got.

#587 Parser Options
  CHANGELOG.md
  Documentation/Commands/colors.md
  Documentation/Commands/coredata.md
  Documentation/Commands/fonts.md
  Documentation/Commands/ib.md
  Documentation/Commands/json.md
  Documentation/Commands/plist.md
  Documentation/Commands/strings.md
  Documentation/Commands/xcassets.md
  Documentation/Commands/yaml.md
  Documentation/ConfigFile.md
  Documentation/SwiftGenKit Contexts/Assets.md
  Sources/SwiftGen/Commander/ParserCLICommands.swift
  Sources/SwiftGen/Config/ConfigEntry.swift
  Sources/SwiftGen/Config/ConfigOutput.swift
  Sources/SwiftGenKit/Parsers/Yaml/YamlParser.swift
  SwiftGen.xcodeproj/project.pbxproj
Labels: type: enhancement

#588 Strings: custom separator option
  CHANGELOG.md
  Documentation/Commands/strings.md
  Documentation/SwiftGenKit Contexts/Strings.md
  Sources/SwiftGenKit/Parsers/Strings/StringsEntry.swift
  Sources/SwiftGenKit/Parsers/Strings/StringsParser.swift
  Tests/Fixtures/Generated/Strings/flat-swift3-context-localizable-customName.swift
  Tests/Fixtures/Generated/Strings/flat-swift3-context-localizable-noComments.swift
  Tests/Fixtures/Generated/Strings/flat-swift3-context-localizable-publicAccess.swift
  Tests/Fixtures/Generated/Strings/flat-swift3-context-localizable.swift
  Tests/Fixtures/Generated/Strings/flat-swift3-context-multiple.swift
  Tests/Fixtures/Generated/Strings/flat-swift4-context-localizable-customName.swift
  Tests/Fixtures/Generated/Strings/flat-swift4-context-localizable-noComments.swift
  Tests/Fixtures/Generated/Strings/flat-swift4-context-localizable-publicAccess.swift
  Tests/Fixtures/Generated/Strings/flat-swift4-context-localizable.swift
  Tests/Fixtures/Generated/Strings/flat-swift4-context-multiple.swift
  Tests/Fixtures/Generated/Strings/structured-swift3-context-localizable-customName.swift
  Tests/Fixtures/Generated/Strings/structured-swift3-context-localizable-noComments.swift
  Tests/Fixtures/Generated/Strings/structured-swift3-context-localizable-publicAccess.swift
  Tests/Fixtures/Generated/Strings/structured-swift3-context-localizable.swift
  Tests/Fixtures/Generated/Strings/structured-swift3-context-multiple.swift
  Tests/Fixtures/Generated/Strings/structured-swift4-context-localizable-customName.swift
  Tests/Fixtures/Generated/Strings/structured-swift4-context-localizable-noComments.swift
  Tests/Fixtures/Generated/Strings/structured-swift4-context-localizable-publicAccess.swift
  Tests/Fixtures/Generated/Strings/structured-swift4-context-localizable.swift
  Tests/Fixtures/Generated/Strings/structured-swift4-context-multiple.swift
  Tests/Fixtures/Resources/Strings/Localizable.strings
  Tests/Fixtures/StencilContexts/Strings/custom-separator.yaml
  Tests/Fixtures/StencilContexts/Strings/localizable.yaml
  Tests/Fixtures/StencilContexts/Strings/multiple.yaml
  Tests/SwiftGenKitTests/StringsTests.swift
Labels: type: enhancement

#593 CoreData: enum attributes
  CHANGELOG.md
  Documentation/templates/coredata/swift3.md
  Documentation/templates/coredata/swift4.md
  Tests/Fixtures/CompilationEnvironment/Definitions.swift
  Tests/Fixtures/CompilationEnvironment/PublicDefinitions.swift
  Tests/Fixtures/Generated/CoreData/swift3-context-defaults-extraImports.swift
  Tests/Fixtures/Generated/CoreData/swift3-context-defaults-generateObjcName.swift
  Tests/Fixtures/Generated/CoreData/swift3-context-defaults-importCoreLocation.swift
  Tests/Fixtures/Generated/CoreData/swift3-context-defaults-publicAccess.swift
  Tests/Fixtures/Generated/CoreData/swift3-context-defaults.swift
  Tests/Fixtures/Generated/CoreData/swift4-context-defaults-extraImports.swift
  Tests/Fixtures/Generated/CoreData/swift4-context-defaults-generateObjcName.swift
  Tests/Fixtures/Generated/CoreData/swift4-context-defaults-importCoreLocation.swift
  Tests/Fixtures/Generated/CoreData/swift4-context-defaults-publicAccess.swift
  Tests/Fixtures/Generated/CoreData/swift4-context-defaults.swift
  Tests/Fixtures/Resources/CoreData/Model.xcdatamodeld/Model 2.xcdatamodel/contents
  Tests/Fixtures/StencilContexts/CoreData/defaults.yaml
  templates/coredata/swift3.stencil
  templates/coredata/swift4.stencil
Labels: type: enhancement

#589 Assets: improve colors performance
  CHANGELOG.md
  Tests/Fixtures/Generated/XCAssets/swift3-context-all-allValues.swift
  Tests/Fixtures/Generated/XCAssets/swift3-context-all-customName.swift
  Tests/Fixtures/Generated/XCAssets/swift3-context-all-forceNamespaces.swift
  Tests/Fixtures/Generated/XCAssets/swift3-context-all-publicAccess.swift
  Tests/Fixtures/Generated/XCAssets/swift3-context-all.swift
  Tests/Fixtures/Generated/XCAssets/swift4-context-all-allValues.swift
  Tests/Fixtures/Generated/XCAssets/swift4-context-all-customName.swift
  Tests/Fixtures/Generated/XCAssets/swift4-context-all-forceNamespaces.swift
  Tests/Fixtures/Generated/XCAssets/swift4-context-all-publicAccess.swift
  Tests/Fixtures/Generated/XCAssets/swift4-context-all.swift
  templates/xcassets/swift3.stencil
  templates/xcassets/swift4.stencil
Labels: type: bug/fix

#599 Tests: compile output using config files
  CHANGELOG.md
  Tests/Fixtures/CompilationEnvironment/CoreData-Definitions.swift
  Tests/Fixtures/CompilationEnvironment/CoreData-ModuleTypes.swift
  Tests/Fixtures/CompilationEnvironment/Definitions.swift
  Tests/Fixtures/CompilationEnvironment/IB-iOS-Definitions.swift
  Tests/Fixtures/CompilationEnvironment/IB-iOS-Login.swift
  Tests/Fixtures/CompilationEnvironment/IB-iOS-NamespacedLogin.swift
  Tests/Fixtures/CompilationEnvironment/IB-macOS-Definitions.swift
  Tests/Fixtures/CompilationEnvironment/IB-macOS-Login.swift
  Tests/Fixtures/CompilationEnvironment/IB-macOS-NamespacedLogin.swift
  Tests/Fixtures/CompilationEnvironment/PublicDefinitions.swift
  Tests/Fixtures/Generated/Colors/literals-swift3/compilation-configuration.yml
  Tests/Fixtures/Generated/Colors/literals-swift4/compilation-configuration.yml
  Tests/Fixtures/Generated/Colors/swift3/compilation-configuration.yml
  Tests/Fixtures/Generated/Colors/swift4/compilation-configuration.yml
  Tests/Fixtures/Generated/CoreData/swift3/compilation-configuration.yml
  Tests/Fixtures/Generated/CoreData/swift4/compilation-configuration.yml
  Tests/Fixtures/Generated/Fonts/swift3/compilation-configuration.yml
  Tests/Fixtures/Generated/Fonts/swift4/compilation-configuration.yml
  Tests/Fixtures/Generated/IB-iOS/scenes-swift3/compilation-configuration.yml
  Tests/Fixtures/Generated/IB-iOS/scenes-swift4/compilation-configuration.yml
  Tests/Fixtures/Generated/IB-iOS/segues-swift3/compilation-configuration.yml
  Tests/Fixtures/Generated/IB-iOS/segues-swift4/compilation-configuration.yml
  Tests/Fixtures/Generated/IB-macOS/scenes-swift3/compilation-configuration.yml
  Tests/Fixtures/Generated/IB-macOS/scenes-swift4/compilation-configuration.yml
  Tests/Fixtures/Generated/IB-macOS/segues-swift3/compilation-configuration.yml
  Tests/Fixtures/Generated/IB-macOS/segues-swift4/compilation-configuration.yml
  Tests/Fixtures/Generated/JSON/inline-swift3/compilation-configuration.yml
  Tests/Fixtures/Generated/JSON/inline-swift4/compilation-configuration.yml
  Tests/Fixtures/Generated/JSON/runtime-swift3/compilation-configuration.yml
  Tests/Fixtures/Generated/JSON/runtime-swift4/compilation-configuration.yml
  Tests/Fixtures/Generated/Plist/inline-swift3/compilation-configuration.yml
  Tests/Fixtures/Generated/Plist/inline-swift4/compilation-configuration.yml
  Tests/Fixtures/Generated/Plist/runtime-swift3/compilation-configuration.yml
  Tests/Fixtures/Generated/Plist/runtime-swift4/compilation-configuration.yml
  Tests/Fixtures/Generated/Strings/flat-swift3/compilation-configuration.yml
  Tests/Fixtures/Generated/Strings/flat-swift4/compilation-configuration.yml
  Tests/Fixtures/Generated/Strings/structured-swift3/compilation-configuration.yml
  Tests/Fixtures/Generated/Strings/structured-swift4/compilation-configuration.yml
  Tests/Fixtures/Generated/XCAssets/swift3/compilation-configuration.yml
  Tests/Fixtures/Generated/XCAssets/swift4/compilation-configuration.yml
  Tests/Fixtures/Generated/YAML/inline-swift3/compilation-configuration.yml
  Tests/Fixtures/Generated/YAML/inline-swift4/compilation-configuration.yml
  rakelib/CompilationConfiguration.rb
  rakelib/output.rake
Labels: type: internal

#573 Strings: Allow specifying localization macro
  CHANGELOG.md
  Documentation/templates/strings/flat-swift3.md
  Documentation/templates/strings/flat-swift4.md
  Documentation/templates/strings/structured-swift3.md
  Documentation/templates/strings/structured-swift4.md
  Tests/Fixtures/CompilationEnvironment/Strings-LocalizeFunction.swift
  Tests/Fixtures/Generated/Strings/flat-swift3/localizable-localizeFunction.swift
  Tests/Fixtures/Generated/Strings/flat-swift4/compilation-configuration.yml
  Tests/Fixtures/Generated/Strings/flat-swift4/localizable-localizeFunction.swift
  Tests/Fixtures/Generated/Strings/structured-swift3/localizable-localizeFunction.swift
  Tests/Fixtures/Generated/Strings/structured-swift4/compilation-configuration.yml
  Tests/Fixtures/Generated/Strings/structured-swift4/localizable-localizeFunction.swift
  Tests/TemplatesTests/StringsTests.swift
  templates/strings/flat-swift3.stencil
  templates/strings/flat-swift4.stencil
  templates/strings/structured-swift3.stencil
  templates/strings/structured-swift4.stencil
Labels: type: enhancement

#602 CocoaPods 1.6.0 #trivial
  Gemfile
  Gemfile.lock
  Podfile.lock
  Pods/Manifest.lock
Labels: type: internal

#596 Document dependencies #trivial
  DEPENDENCIES.md
  Dangerfile
  rakelib/dependencies.rake
  rakelib/utils.rake
Labels: type: documentation, type: internal

#606 Add a help message if there's an error #trivial
  Sources/SwiftGen/Commander/ConfigCommands.swift
  Sources/SwiftGen/Config/Config.swift
  Tests/SwiftGenTests/ConfigLintTests.swift
Labels: type: enhancement

#607 Fix readme typos & erratums #trivial
  README.md
Labels: type: documentation

#597 Parser Options - Part 2: Safety
  CHANGELOG.md
  Sources/SwiftGen/Commander/ConfigCommands.swift
  Sources/SwiftGen/Commander/ParserCLICommands.swift
  Sources/SwiftGen/Config/Config.swift
  Sources/SwiftGenKit/Parsers/AssetsCatalog/AssetsCatalogParser.swift
  Sources/SwiftGenKit/Parsers/Colors/ColorsCLRFileParser.swift
  Sources/SwiftGenKit/Parsers/Colors/ColorsFileTypeParser.swift
  Sources/SwiftGenKit/Parsers/Colors/ColorsJSONFileParser.swift
  Sources/SwiftGenKit/Parsers/Colors/ColorsParser.swift
  Sources/SwiftGenKit/Parsers/Colors/ColorsTXTFileParser.swift
  Sources/SwiftGenKit/Parsers/Colors/ColorsXMLFileParser.swift
  Sources/SwiftGenKit/Parsers/CoreData/CoreDataParser.swift
  Sources/SwiftGenKit/Parsers/Fonts/FontsParser.swift
  Sources/SwiftGenKit/Parsers/InterfaceBuilder/InterfaceBuilderParser.swift
  Sources/SwiftGenKit/Parsers/Parser.swift
  Sources/SwiftGenKit/Parsers/ParserOption.swift
  Sources/SwiftGenKit/Parsers/ParserOptionList.swift
  Sources/SwiftGenKit/Parsers/ParserOptionValues.swift
  Sources/SwiftGenKit/Parsers/Plist/PlistParser.swift
  Sources/SwiftGenKit/Parsers/Strings/StringsEntry.swift
  Sources/SwiftGenKit/Parsers/Strings/StringsParser.swift
  Sources/SwiftGenKit/Parsers/Yaml/YamlParser.swift
  SwiftGen.xcodeproj/project.pbxproj
  Tests/SwiftGenKitTests/AssetCatalogTests.swift
  Tests/SwiftGenKitTests/ColorsCLRFileTests.swift
  Tests/SwiftGenKitTests/ColorsJSONFileTests.swift
  Tests/SwiftGenKitTests/ColorsTests.swift
  Tests/SwiftGenKitTests/ColorsTextFileTests.swift
  Tests/SwiftGenKitTests/ColorsXMLFileTests.swift
  Tests/SwiftGenKitTests/CoreDataTests.swift
  Tests/SwiftGenKitTests/FontsTests.swift
  Tests/SwiftGenKitTests/InterfaceBuilderMacOSTests.swift
  Tests/SwiftGenKitTests/InterfaceBuilderiOSTests.swift
  Tests/SwiftGenKitTests/PlistTests.swift
  Tests/SwiftGenKitTests/StringsTests.swift
  Tests/SwiftGenKitTests/YamlTests.swift
Labels: type: enhancement
