Repository SwiftGen/SwiftGen, pull requests merged in 2020-06, with the labels that each got.

#714 Renamed "master" branch to "stable" #trivial
  CHANGELOG.md
  DEPENDENCIES.md
  Documentation/MigrationGuide.md
  Documentation/templates/MigrationGuide.md
Labels: type: internal

#713 Update documentation folder
  CHANGELOG.md
  Documentation/Articles/Creating-custom-templates.md
  Documentation/Creating-your-templates.md
  Documentation/MigrationGuide.md
  Documentation/Parsers/colors.md
  Documentation/Parsers/coredata.md
  Documentation/Parsers/fonts.md
  Documentation/Parsers/ib.md
  Documentation/Parsers/json.md
  Documentation/Parsers/plist.md
  Documentation/Parsers/strings.md
  Documentation/Parsers/xcassets.md
  Documentation/Parsers/yaml.md
  Documentation/README.md
  Documentation/SwiftGenKit Contexts/Strings.md
  Documentation/templates/json/runtime-swift4.md
  Documentation/templates/json/runtime-swift5.md
  Documentation/templates/plist/runtime-swift4.md
  Documentation/templates/plist/runtime-swift5.md
Labels: type: documentation

#715 Update playground before 6.2.0 release #trivial
  CHANGELOG.md
  SwiftGen.playground/Pages/Colors-Demo.xcplaygroundpage/Contents.swift
  SwiftGen.playground/Pages/InterfaceBuilder-Demo.xcplaygroundpage/Contents.swift
  SwiftGen.playground/Pages/XCAssets-Demo.xcplaygroundpage/Contents.swift
  SwiftGen.playground/Resources/Assets.car
  SwiftGen.playground/Resources/Localizable.strings
  SwiftGen.playground/Resources/Model.momd/Model 2.mom
  SwiftGen.playground/Resources/Model.momd/Model 2.omo
  SwiftGen.playground/Resources/Model.momd/Model.mom
  SwiftGen.playground/Resources/Wizard.storyboardc/30h-14-fok-view-rJE-c0-6Bp.nib
  SwiftGen.playground/Resources/Wizard.storyboardc/Accept-ToS.nib
  SwiftGen.playground/Resources/Wizard.storyboardc/CreateAccount.nib
  SwiftGen.playground/Resources/Wizard.storyboardc/Info.plist
  SwiftGen.playground/Resources/Wizard.storyboardc/Preferences.nib
  SwiftGen.playground/Resources/Wizard.storyboardc/Validate_Password.nib
  SwiftGen.playground/Resources/Wizard.storyboardc/designable.storyboard
  SwiftGen.playground/Resources/Wizard.storyboardc/rJ7-m2-Mn7-view-wtR-sc-VB5.nib
  SwiftGen.playground/Resources/Wizard.storyboardc/txY-Mc-CKa-view-wQH-MG-v6Y.nib
  SwiftGen.playground/Resources/Wizard.storyboardc/w6o-YQ-YLg-view-N1u-m6-6Oc.nib
  Tests/Fixtures/Resources/XCAssets/Styles.xcassets/Vengo/Primary.colorset/Contents.json
Labels: type: documentation, type: internal

#716 Strings: better `localizeFunction`
  CHANGELOG.md
  Documentation/templates/strings/flat-swift4.md
  Documentation/templates/strings/flat-swift5.md
  Documentation/templates/strings/structured-swift4.md
  Documentation/templates/strings/structured-swift5.md
  SwiftGen.playground/Pages/Strings-Demo.xcplaygroundpage/Contents.swift
  Tests/Fixtures/CompilationEnvironment/Strings-LocalizeFunction.swift
  Tests/Fixtures/Generated/Strings/flat-swift4/compilation-configuration.yml
  Tests/Fixtures/Generated/Strings/flat-swift4/localizable-customName.swift
  Tests/Fixtures/Generated/Strings/flat-swift4/localizable-forceFileNameEnum.swift
  Tests/Fixtures/Generated/Strings/flat-swift4/localizable-lookupFunction.swift
  Tests/Fixtures/Generated/Strings/flat-swift4/localizable-noComments.swift
  Tests/Fixtures/Generated/Strings/flat-swift4/localizable-publicAccess.swift
  Tests/Fixtures/Generated/Strings/flat-swift4/localizable.swift
  Tests/Fixtures/Generated/Strings/flat-swift4/multiple.swift
  Tests/Fixtures/Generated/Strings/flat-swift5/compilation-configuration.yml
  Tests/Fixtures/Generated/Strings/flat-swift5/localizable-customName.swift
  Tests/Fixtures/Generated/Strings/flat-swift5/localizable-forceFileNameEnum.swift
  Tests/Fixtures/Generated/Strings/flat-swift5/localizable-lookupFunction.swift
  Tests/Fixtures/Generated/Strings/flat-swift5/localizable-noComments.swift
  Tests/Fixtures/Generated/Strings/flat-swift5/localizable-publicAccess.swift
  Tests/Fixtures/Generated/Strings/flat-swift5/localizable.swift
  Tests/Fixtures/Generated/Strings/flat-swift5/multiple.swift
  Tests/Fixtures/Generated/Strings/objc-h/localizable-noComments.h
  Tests/Fixtures/Generated/Strings/objc-m/localizable-headerName.m
  Tests/Fixtures/Generated/Strings/objc-m/localizable-noComments.m
  Tests/Fixtures/Generated/Strings/objc-m/localizable.m
  Tests/Fixtures/Generated/Strings/objc-m/multiple.m
  Tests/Fixtures/Generated/Strings/structured-swift4/compilation-configuration.yml
  Tests/Fixtures/Generated/Strings/structured-swift4/localizable-customName.swift
  Tests/Fixtures/Generated/Strings/structured-swift4/localizable-forceFileNameEnum.swift
  Tests/Fixtures/Generated/Strings/structured-swift4/localizable-lookupFunction.swift
  Tests/Fixtures/Generated/Strings/structured-swift4/localizable-noComments.swift
  Tests/Fixtures/Generated/Strings/structured-swift4/localizable-publicAccess.swift
  Tests/Fixtures/Generated/Strings/structured-swift4/localizable.swift
  Tests/Fixtures/Generated/Strings/structured-swift4/multiple.swift
  Tests/Fixtures/Generated/Strings/structured-swift5/compilation-configuration.yml
  Tests/Fixtures/Generated/Strings/structured-swift5/localizable-customName.swift
  Tests/Fixtures/Generated/Strings/structured-swift5/localizable-forceFileNameEnum.swift
  Tests/Fixtures/Generated/Strings/structured-swift5/localizable-lookupFunction.swift
  Tests/Fixtures/Generated/Strings/structured-swift5/localizable-noComments.swift
  Tests/Fixtures/Generated/Strings/structured-swift5/localizable-publicAccess.swift
  Tests/Fixtures/Generated/Strings/structured-swift5/localizable.swift
  Tests/Fixtures/Generated/Strings/structured-swift5/multiple.swift
  Tests/TemplatesTests/StringsTests.swift
  templates/strings/flat-swift4.stencil
  templates/strings/flat-swift5.stencil
  templates/strings/objc-m.stencil
  templates/strings/structured-swift4.stencil
  templates/strings/structured-swift5.stencil
Labels: type: bug/fix

#717 Deprecate Application Support and Update Migration Guides
  CHANGELOG.md
  Documentation/MigrationGuide.md
  Documentation/templates/MigrationGuide.md
  Sources/SwiftGen/Commander/TemplateCommands.swift
  Sources/SwiftGen/Path+CommonLocations.swift
  Sources/SwiftGen/TemplateRef.swift
  SwiftGen.xcodeproj/project.pbxproj
Labels: type: documentation

#710 Colors: Fix long expression type check warning
  CHANGELOG.md
  Tests/Fixtures/Generated/Colors/swift4/defaults-customName.swift
  Tests/Fixtures/Generated/Colors/swift4/defaults-forceFileNameEnum.swift
  Tests/Fixtures/Generated/Colors/swift4/defaults-publicAccess.swift
  Tests/Fixtures/Generated/Colors/swift4/defaults.swift
  Tests/Fixtures/Generated/Colors/swift4/multiple.swift
  Tests/Fixtures/Generated/Colors/swift5/defaults-customName.swift
  Tests/Fixtures/Generated/Colors/swift5/defaults-forceFileNameEnum.swift
  Tests/Fixtures/Generated/Colors/swift5/defaults-publicAccess.swift
  Tests/Fixtures/Generated/Colors/swift5/defaults.swift
  Tests/Fixtures/Generated/Colors/swift5/multiple.swift
  templates/colors/swift4.stencil
  templates/colors/swift5.stencil
Labels: status: ready to merge (waiting for CI), type: bug/fix, type: enhancement

#720 README fixes #trivial
  README.md
Labels: type: documentation

#722 Fix: revert code coverage
  CHANGELOG.md
  SwiftGen.xcodeproj/xcshareddata/xcschemes/swiftgen.xcscheme
Labels: type: bug/fix

#708 Run commands in parallel
  CHANGELOG.md
  Sources/SwiftGen/Array+Parallel.swift
  Sources/SwiftGen/Commander/ConfigCommands.swift
  Sources/SwiftGen/Commander/OutputDestination.swift
  Sources/SwiftGen/Config/Config+Run.swift
  Sources/SwiftGen/Config/Config.swift
  Sources/SwiftGen/Config/ConfigEntry.swift
  Sources/SwiftGen/Logs.swift
  Sources/SwiftGen/ParserCLI.swift
  Sources/SwiftGen/TemplateRef.swift
  SwiftGen.xcodeproj/project.pbxproj
  Tests/Fixtures/Configs/config-invalid-parsers.yml
  Tests/SwiftGenKitTests/AssetCatalogTests.swift
  Tests/SwiftGenKitTests/ColorsCLRFileTests.swift
  Tests/SwiftGenKitTests/ColorsJSONFileTests.swift
  Tests/SwiftGenKitTests/ColorsTests.swift
  Tests/SwiftGenKitTests/ColorsTextFileTests.swift
  Tests/SwiftGenKitTests/ColorsXMLFileTests.swift
  Tests/SwiftGenKitTests/CoreDataTests.swift
  Tests/SwiftGenKitTests/FilterTests.swift
  Tests/SwiftGenKitTests/FontsTests.swift
  Tests/SwiftGenKitTests/InterfaceBuilderMacOSTests.swift
  Tests/SwiftGenKitTests/InterfaceBuilderiOSTests.swift
  Tests/SwiftGenKitTests/PlistTests.swift
  Tests/SwiftGenKitTests/StringParserTests.swift
  Tests/SwiftGenKitTests/StringsTests.swift
  Tests/SwiftGenKitTests/YamlTests.swift
  Tests/SwiftGenTests/ConfigInitTests.swift
  Tests/SwiftGenTests/ConfigLintTests.swift
  Tests/SwiftGenTests/ConfigReadTests.swift
  Tests/SwiftGenTests/ConfigRunTests.swift
  Tests/SwiftGenTests/TestsHelper.swift
  Tests/TemplatesTests/ColorsTests.swift
  Tests/TemplatesTests/CoreDataTests.swift
  Tests/TemplatesTests/FontsTests.swift
  Tests/TemplatesTests/InterfaceBuilderMacOSTests.swift
  Tests/TemplatesTests/InterfaceBuilderiOSTests.swift
  Tests/TemplatesTests/JsonTests.swift
  Tests/TemplatesTests/PlistTests.swift
  Tests/TemplatesTests/StringsTests.swift
  Tests/TemplatesTests/XCAssetsTests.swift
  Tests/TemplatesTests/YamlTests.swift
Labels: type: enhancement

#687 Fix issue with Array in the Inline templates
  CHANGELOG.md
  Tests/Fixtures/Generated/JSON/inline-swift4/all-customName.swift
  Tests/Fixtures/Generated/JSON/inline-swift4/all-forceFileNameEnum.swift
  Tests/Fixtures/Generated/JSON/inline-swift4/all-publicAccess.swift
  Tests/Fixtures/Generated/JSON/inline-swift4/all.swift
  Tests/Fixtures/Generated/JSON/inline-swift5/all-customName.swift
  Tests/Fixtures/Generated/JSON/inline-swift5/all-forceFileNameEnum.swift
  Tests/Fixtures/Generated/JSON/inline-swift5/all-publicAccess.swift
  Tests/Fixtures/Generated/JSON/inline-swift5/all.swift
  Tests/Fixtures/Generated/JSON/runtime-swift4/all-customname.swift
  Tests/Fixtures/Generated/JSON/runtime-swift4/all-forceFileNameEnum.swift
  Tests/Fixtures/Generated/JSON/runtime-swift4/all-preservePath.swift
  Tests/Fixtures/Generated/JSON/runtime-swift4/all-publicAccess.swift
  Tests/Fixtures/Generated/JSON/runtime-swift4/all.swift
  Tests/Fixtures/Generated/JSON/runtime-swift5/all-customname.swift
  Tests/Fixtures/Generated/JSON/runtime-swift5/all-forceFileNameEnum.swift
  Tests/Fixtures/Generated/JSON/runtime-swift5/all-preservePath.swift
  Tests/Fixtures/Generated/JSON/runtime-swift5/all-publicAccess.swift
  Tests/Fixtures/Generated/JSON/runtime-swift5/all.swift
  Tests/Fixtures/Generated/Plist/inline-swift4/all-customname.swift
  Tests/Fixtures/Generated/Plist/inline-swift4/all-forceFileNameEnum.swift
  Tests/Fixtures/Generated/Plist/inline-swift4/all-publicAccess.swift
  Tests/Fixtures/Generated/Plist/inline-swift4/all.swift
  Tests/Fixtures/Generated/Plist/inline-swift5/all-customname.swift
  Tests/Fixtures/Generated/Plist/inline-swift5/all-forceFileNameEnum.swift
  Tests/Fixtures/Generated/Plist/inline-swift5/all-publicAccess.swift
  Tests/Fixtures/Generated/Plist/inline-swift5/all.swift
  Tests/Fixtures/Generated/Plist/runtime-swift4/all-customName.swift
  Tests/Fixtures/Generated/Plist/runtime-swift4/all-forceFileNameEnum.swift
  Tests/Fixtures/Generated/Plist/runtime-swift4/all-preservePath.swift
  Tests/Fixtures/Generated/Plist/runtime-swift4/all-publicAccess.swift
  Tests/Fixtures/Generated/Plist/runtime-swift4/all.swift
  Tests/Fixtures/Generated/Plist/runtime-swift5/all-customName.swift
  Tests/Fixtures/Generated/Plist/runtime-swift5/all-forceFileNameEnum.swift
  Tests/Fixtures/Generated/Plist/runtime-swift5/all-preservePath.swift
  Tests/Fixtures/Generated/Plist/runtime-swift5/all-publicAccess.swift
  Tests/Fixtures/Generated/Plist/runtime-swift5/all.swift
  Tests/Fixtures/Generated/YAML/inline-swift4/all-customName.swift
  Tests/Fixtures/Generated/YAML/inline-swift4/all-forceFileNameEnum.swift
  Tests/Fixtures/Generated/YAML/inline-swift4/all-publicAccess.swift
  Tests/Fixtures/Generated/YAML/inline-swift4/all.swift
  Tests/Fixtures/Generated/YAML/inline-swift5/all-customName.swift
  Tests/Fixtures/Generated/YAML/inline-swift5/all-forceFileNameEnum.swift
  Tests/Fixtures/Generated/YAML/inline-swift5/all-publicAccess.swift
  Tests/Fixtures/Generated/YAML/inline-swift5/all.swift
  Tests/Fixtures/Resources/Plist/good/configuration.plist
  Tests/Fixtures/Resources/YAML/good/mapping.yaml
  Tests/Fixtures/StencilContexts/Plist/all.yaml
  Tests/Fixtures/StencilContexts/Plist/configuration.yaml
  Tests/Fixtures/StencilContexts/Yaml/all.yaml
  Tests/Fixtures/StencilContexts/Yaml/mapping.yaml
  templates/json/inline-swift4.stencil
  templates/json/inline-swift5.stencil
  templates/plist/inline-swift4.stencil
  templates/plist/inline-swift5.stencil
  templates/yaml/inline-swift4.stencil
  templates/yaml/inline-swift5.stencil
Labels: type: bug/fix

#730 Fix breaking swift when installing via Homebrew
  CHANGELOG.md
  README.md
  Rakefile
Labels: type: bug/fix

#729 Small code improvements #trivial
  Documentation/Articles/Making-CI-check-SwiftGen-changes.md
  Documentation/ConfigFile.md
  README.md
  Sources/SwiftGenKit/Parsers/AssetsCatalog/AssetsCatalogParser.swift
  Sources/SwiftGenKit/Parsers/Colors/ColorsParser.swift
  Sources/SwiftGenKit/Parsers/CoreData/CoreDataParser.swift
  Sources/SwiftGenKit/Parsers/Filter.swift
  Sources/SwiftGenKit/Parsers/Fonts/FontsParser.swift
  Sources/SwiftGenKit/Parsers/InterfaceBuilder/InterfaceBuilderParser.swift
  Sources/SwiftGenKit/Parsers/JSON/JSONParser.swift
  Sources/SwiftGenKit/Parsers/Plist/PlistParser.swift
  Sources/SwiftGenKit/Parsers/Strings/StringsParser.swift
  Sources/SwiftGenKit/Parsers/Yaml/YamlParser.swift
  Sources/SwiftGenKit/Stencil/AssetsCatalogParser+Context.swift
  Sources/SwiftGenKit/Stencil/ColorsParser+Context.swift
  Sources/SwiftGenKit/Stencil/CoreDataParser+Context.swift
  Sources/SwiftGenKit/Stencil/FontsParser+Context.swift
  Sources/SwiftGenKit/Stencil/InterfaceBuilderParser+Context.swift
  Sources/SwiftGenKit/Stencil/JSONParser+Context.swift
  Sources/SwiftGenKit/Stencil/PlistParser+Context.swift
  Sources/SwiftGenKit/Stencil/StringsParser+Context.swift
  Sources/SwiftGenKit/Stencil/YamlParser+Context.swift
  SwiftGen.playground/Pages/Colors-Demo.xcplaygroundpage/Contents.swift
  SwiftGen.playground/Pages/CoreData-Demo.xcplaygroundpage/Contents.swift
  SwiftGen.playground/Pages/Fonts-Demo.xcplaygroundpage/Contents.swift
  SwiftGen.playground/Pages/InterfaceBuilder-Demo.xcplaygroundpage/Contents.swift
  SwiftGen.playground/Pages/JSON-Demo.xcplaygroundpage/Contents.swift
  SwiftGen.playground/Pages/Plist-Demo.xcplaygroundpage/Contents.swift
  SwiftGen.playground/Pages/Strings-Demo.xcplaygroundpage/Contents.swift
  SwiftGen.playground/Pages/XCAssets-Demo.xcplaygroundpage/Contents.swift
  SwiftGen.playground/Pages/YAML-Demo.xcplaygroundpage/Contents.swift
  SwiftGen.xcodeproj/project.pbxproj
Labels: status: ready to merge (waiting for CI), type: internal
