Repository SwiftGen/SwiftGen, pull requests merged in 2020-07, with the labels that each got.

#709 Lazily evaluate `metadata` in JSON/Plist/YAML parsers
  CHANGELOG.md
  Sources/SwiftGenKit/Stencil/ContextHelpers.swift
  Sources/SwiftGenKit/Stencil/JSONParser+Context.swift
  Sources/SwiftGenKit/Stencil/PlistParser+Context.swift
  Sources/SwiftGenKit/Stencil/YamlParser+Context.swift
  SwiftGen.xcodeproj/project.pbxproj
  Tests/SwiftGenKitTests/TestsHelper.swift
Labels: type: enhancement, type: internal

#728 Fonts: parameters to change typealias name & struct name
  CHANGELOG.md
  Documentation/templates/fonts/swift4.md
  Documentation/templates/fonts/swift5.md
  Tests/Fixtures/Generated/Fonts/swift4/defaults-customName.swift
  Tests/Fixtures/Generated/Fonts/swift4/defaults-preservePath.swift
  Tests/Fixtures/Generated/Fonts/swift4/defaults-publicAccess.swift
  Tests/Fixtures/Generated/Fonts/swift4/defaults.swift
  Tests/Fixtures/Generated/Fonts/swift5/defaults-customName.swift
  Tests/Fixtures/Generated/Fonts/swift5/defaults-preservePath.swift
  Tests/Fixtures/Generated/Fonts/swift5/defaults-publicAccess.swift
  Tests/Fixtures/Generated/Fonts/swift5/defaults.swift
  Tests/TemplatesTests/FontsTests.swift
  templates/fonts/swift4.stencil
  templates/fonts/swift5.stencil
Labels: type: enhancement

#742 [Internal] Use linguist gitattributes to improve GitHub diffs in PRs and lang stats #trivial
  .gitattributes
Labels: type: internal

#726 CoreData: Change fetchRequest to makeFetchRequest
  CHANGELOG.md
  Documentation/templates/coredata/swift4.md
  Documentation/templates/coredata/swift5.md
  README.md
  SwiftGen.playground/Pages/CoreData-Demo.xcplaygroundpage/Contents.swift
  Tests/Fixtures/Generated/CoreData/swift4/defaults-extraImports.swift
  Tests/Fixtures/Generated/CoreData/swift4/defaults-generateObjcName.swift
  Tests/Fixtures/Generated/CoreData/swift4/defaults-importCoreLocation.swift
  Tests/Fixtures/Generated/CoreData/swift4/defaults-publicAccess.swift
  Tests/Fixtures/Generated/CoreData/swift4/defaults.swift
  Tests/Fixtures/Generated/CoreData/swift5/defaults-extraImports.swift
  Tests/Fixtures/Generated/CoreData/swift5/defaults-generateObjcName.swift
  Tests/Fixtures/Generated/CoreData/swift5/defaults-importCoreLocation.swift
  Tests/Fixtures/Generated/CoreData/swift5/defaults-publicAccess.swift
  Tests/Fixtures/Generated/CoreData/swift5/defaults.swift
  templates/coredata/swift4.stencil
  templates/coredata/swift5.stencil
Labels: type: enhancement

#745 [Internal] Improve experience in PR reviews #trivial
  .gitattributes
  CHANGELOG.md
  rakelib/check_changelog.rb
Labels: type: internal

#733 XCAssets: image loading performance on macOS
  CHANGELOG.md
  Tests/Fixtures/Generated/XCAssets/swift4/all-allValues.swift
  Tests/Fixtures/Generated/XCAssets/swift4/all-customName.swift
  Tests/Fixtures/Generated/XCAssets/swift4/all-forceFileNameEnum.swift
  Tests/Fixtures/Generated/XCAssets/swift4/all-forceNamespaces.swift
  Tests/Fixtures/Generated/XCAssets/swift4/all-publicAccess.swift
  Tests/Fixtures/Generated/XCAssets/swift4/all.swift
  Tests/Fixtures/Generated/XCAssets/swift4/food.swift
  Tests/Fixtures/Generated/XCAssets/swift5/all-allValues.swift
  Tests/Fixtures/Generated/XCAssets/swift5/all-customName.swift
  Tests/Fixtures/Generated/XCAssets/swift5/all-forceFileNameEnum.swift
  Tests/Fixtures/Generated/XCAssets/swift5/all-forceNamespaces.swift
  Tests/Fixtures/Generated/XCAssets/swift5/all-publicAccess.swift
  Tests/Fixtures/Generated/XCAssets/swift5/all.swift
  Tests/Fixtures/Generated/XCAssets/swift5/food.swift
  templates/xcassets/swift4.stencil
  templates/xcassets/swift5.stencil
Labels: type: enhancement

#738 Template `lookupFunction` parameter
  CHANGELOG.md
  Dangerfile
  Documentation/Articles/Customize-loading-of-resources.md
  Documentation/Articles/SwiftLint-Integration.md
  Documentation/README.md
  Documentation/templates/fonts/swift4.md
  Documentation/templates/fonts/swift5.md
  Documentation/templates/ib/scenes-swift4.md
  Documentation/templates/ib/scenes-swift5.md
  Documentation/templates/json/runtime-swift4.md
  Documentation/templates/json/runtime-swift5.md
  Documentation/templates/plist/runtime-swift4.md
  Documentation/templates/plist/runtime-swift5.md
  Documentation/templates/strings/flat-swift4.md
  Documentation/templates/strings/flat-swift5.md
  Documentation/templates/strings/structured-swift4.md
  Documentation/templates/strings/structured-swift5.md
  Sources/SwiftGen/Config/Config+Example.swift
  Tests/Fixtures/CompilationEnvironment/Common-LookupFunction.swift
  Tests/Fixtures/CompilationEnvironment/Strings-LocalizeFunction.swift
  Tests/Fixtures/Generated/Fonts/swift4/compilation-configuration.yml
  Tests/Fixtures/Generated/Fonts/swift4/defaults-lookupFunction.swift
  Tests/Fixtures/Generated/Fonts/swift5/compilation-configuration.yml
  Tests/Fixtures/Generated/Fonts/swift5/defaults-lookupFunction.swift
  Tests/Fixtures/Generated/IB-iOS/scenes-swift4/all-lookupFunction.swift
  Tests/Fixtures/Generated/IB-iOS/scenes-swift4/compilation-configuration.yml
  Tests/Fixtures/Generated/IB-iOS/scenes-swift5/all-lookupFunction.swift
  Tests/Fixtures/Generated/IB-iOS/scenes-swift5/compilation-configuration.yml
  Tests/Fixtures/Generated/IB-macOS/scenes-swift4/all-lookupFunction.swift
  Tests/Fixtures/Generated/IB-macOS/scenes-swift4/compilation-configuration.yml
  Tests/Fixtures/Generated/IB-macOS/scenes-swift5/all-lookupFunction.swift
  Tests/Fixtures/Generated/IB-macOS/scenes-swift5/compilation-configuration.yml
  Tests/Fixtures/Generated/JSON/runtime-swift4/all-lookupFunction.swift
  Tests/Fixtures/Generated/JSON/runtime-swift4/compilation-configuration.yml
  Tests/Fixtures/Generated/JSON/runtime-swift5/all-lookupFunction.swift
  Tests/Fixtures/Generated/JSON/runtime-swift5/compilation-configuration.yml
  Tests/Fixtures/Generated/Plist/runtime-swift4/all-lookupFunction.swift
  Tests/Fixtures/Generated/Plist/runtime-swift4/compilation-configuration.yml
  Tests/Fixtures/Generated/Plist/runtime-swift5/all-lookupFunction.swift
  Tests/Fixtures/Generated/Plist/runtime-swift5/compilation-configuration.yml
  Tests/Fixtures/Generated/Strings/flat-swift4/compilation-configuration.yml
  Tests/Fixtures/Generated/Strings/flat-swift5/compilation-configuration.yml
  Tests/Fixtures/Generated/Strings/structured-swift4/compilation-configuration.yml
  Tests/Fixtures/Generated/Strings/structured-swift5/compilation-configuration.yml
  Tests/TemplatesTests/FontsTests.swift
  Tests/TemplatesTests/InterfaceBuilderTests.swift
  Tests/TemplatesTests/JsonTests.swift
  Tests/TemplatesTests/PlistTests.swift
  templates/fonts/swift4.stencil
  templates/fonts/swift5.stencil
  templates/ib/scenes-swift4.stencil
  templates/ib/scenes-swift5.stencil
  templates/json/runtime-swift4.stencil
  templates/json/runtime-swift5.stencil
  templates/plist/runtime-swift4.stencil
  templates/plist/runtime-swift5.stencil
Labels: type: enhancement

#749 Fix the list of app arguments in Xcode scheme #trivial
  SwiftGen.xcodeproj/xcshareddata/xcschemes/swiftgen.xcscheme
Labels: type: internal

#751 Fix crash in Dangerfile #trivial
  Dangerfile
Labels: type: bug/fix, type: internal
