Repository SwiftGen/SwiftGen, pull requests merged in 2020-05, with the labels that each got.

#619 Cocoapods 1.9
  .circleci/config.yml
  .ruby-version
  CHANGELOG.md
  Gemfile
  Gemfile.lock
  Podfile
  Podfile.lock
  Pods/.project_cache/installation_cache.yaml
  Pods/.project_cache/metadata_cache.yaml
  Pods/.project_cache/version
  Pods/Commander.xcodeproj/project.pbxproj
  Pods/Kanna.xcodeproj/project.pbxproj
  Pods/Manifest.lock
  Pods/PathKit.xcodeproj/project.pbxproj
  Pods/Pods.xcodeproj/project.pbxproj
  Pods/Stencil.xcodeproj/project.pbxproj
  Pods/StencilSwiftKit.xcodeproj/project.pbxproj
  Pods/SwiftLint.xcodeproj/project.pbxproj
  Pods/Target Support Files/Commander/Commander.debug.xcconfig
  Pods/Target Support Files/Commander/Commander.release.xcconfig
  Pods/Target Support Files/Kanna/Kanna.debug.xcconfig
  Pods/Target Support Files/Kanna/Kanna.release.xcconfig
  Pods/Target Support Files/PathKit/PathKit.debug.xcconfig
  Pods/Target Support Files/PathKit/PathKit.release.xcconfig
  Pods/Target Support Files/Pods-SwiftGenKit-SwiftGenKit UnitTests/Pods-SwiftGenKit-SwiftGenKit UnitTests-frameworks.sh
  Pods/Target Support Files/Pods-SwiftGenKit-SwiftGenKit UnitTests/Pods-SwiftGenKit-SwiftGenKit UnitTests.debug.xcconfig
  Pods/Target Support Files/Pods-SwiftGenKit-SwiftGenKit UnitTests/Pods-SwiftGenKit-SwiftGenKit UnitTests.release.xcconfig
  Pods/Target Support Files/Pods-SwiftGenKit/Pods-SwiftGenKit.debug.xcconfig
  Pods/Target Support Files/Pods-SwiftGenKit/Pods-SwiftGenKit.release.xcconfig
  Pods/Target Support Files/Pods-swiftgen-SwiftGen UnitTests/Pods-swiftgen-SwiftGen UnitTests-frameworks.sh
  Pods/Target Support Files/Pods-swiftgen-SwiftGen UnitTests/Pods-swiftgen-SwiftGen UnitTests.debug.xcconfig
  Pods/Target Support Files/Pods-swiftgen-SwiftGen UnitTests/Pods-swiftgen-SwiftGen UnitTests.release.xcconfig
  Pods/Target Support Files/Pods-swiftgen-Templates UnitTests/Pods-swiftgen-Templates UnitTests-frameworks.sh
  Pods/Target Support Files/Pods-swiftgen-Templates UnitTests/Pods-swiftgen-Templates UnitTests.debug.xcconfig
  Pods/Target Support Files/Pods-swiftgen-Templates UnitTests/Pods-swiftgen-Templates UnitTests.release.xcconfig
  Pods/Target Support Files/Pods-swiftgen/Pods-swiftgen-frameworks.sh
  Pods/Target Support Files/Pods-swiftgen/Pods-swiftgen.debug.xcconfig
  Pods/Target Support Files/Pods-swiftgen/Pods-swiftgen.release.xcconfig
  Pods/Target Support Files/Stencil/Stencil.debug.xcconfig
  Pods/Target Support Files/Stencil/Stencil.release.xcconfig
  Pods/Target Support Files/StencilSwiftKit/StencilSwiftKit.debug.xcconfig
  Pods/Target Support Files/StencilSwiftKit/StencilSwiftKit.release.xcconfig
  Pods/Target Support Files/SwiftLint/SwiftLint.debug.xcconfig
  Pods/Target Support Files/SwiftLint/SwiftLint.release.xcconfig
  Pods/Target Support Files/Yams/Yams.debug.xcconfig
  Pods/Target Support Files/Yams/Yams.release.xcconfig
  Pods/Yams.xcodeproj/project.pbxproj
  SwiftGen.playground/Pages/Colors-Demo.xcplaygroundpage/Contents.swift
  SwiftGen.playground/contents.xcplayground
  SwiftGen.xcodeproj/project.pbxproj
  SwiftGen.xcodeproj/xcshareddata/xcschemes/SwiftGenKit - Generate Contexts.xcscheme
  SwiftGen.xcodeproj/xcshareddata/xcschemes/SwiftGenKit.xcscheme
  SwiftGen.xcodeproj/xcshareddata/xcschemes/Templates - Generate Output.xcscheme
  SwiftGen.xcodeproj/xcshareddata/xcschemes/swiftgen.xcscheme
Labels: type: internal

#692 CoreData: fix missing comma
  CHANGELOG.md
  Tests/Fixtures/Generated/CoreData/swift4/defaults-extraImports.swift
  Tests/Fixtures/Generated/CoreData/swift4/defaults-generateObjcName.swift
  Tests/Fixtures/Generated/CoreData/swift4/defaults-importCoreLocation.swift
  Tests/Fixtures/Generated/CoreData/swift4/defaults-publicAccess.swift
  Tests/Fixtures/Generated/CoreData/swift4/defaults.swift
  Tests/Fixtures/Generated/CoreData/swift5/defaults-extraImports.swift
  Tests/Fixtures/Generated/CoreData/swift5/defaults-generateObjcName.swift
  Tests/Fixtures/Generated/CoreData/swift5/defaults-importCoreLocation.swift
  Tests/Fixtures/Generated/CoreData/swift5/defaults-publicAccess.swift
  Tests/Fixtures/Generated/CoreData/swift5/defaults.swift
  Tests/Fixtures/Resources/CoreData/Model.xcdatamodeld/Model 2.xcdatamodel/contents
  Tests/Fixtures/StencilContexts/CoreData/defaults.yaml
  templates/coredata/swift4.stencil
  templates/coredata/swift5.stencil
Labels: type: bug/fix

#694 swiftgen config init
  CHANGELOG.md
  Documentation/ConfigFile.md
  README.md
  Sources/SwiftGen/Commander/ConfigCommands.swift
  Sources/SwiftGen/Config/Config+Example.swift
  Sources/SwiftGen/Config/Config.swift
  Sources/SwiftGen/Path+CommonLocations.swift
  Sources/SwiftGen/main.swift
  SwiftGen.xcodeproj/project.pbxproj
  SwiftGen.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  SwiftGen.xcodeproj/xcshareddata/IDETemplateMacros.plist
  SwiftGen.xcodeproj/xcshareddata/xcschemes/swiftgen.xcscheme
  Tests/SwiftGenTests/ConfigInitTests.swift
Labels: type: enhancement

#703 Enable code coverage #trivial
  SwiftGen.xcodeproj/xcshareddata/xcschemes/swiftgen.xcscheme
Labels: type: internal

#697 Introduce `swiftgen template doc`
  CHANGELOG.md
  Documentation/Articles/Xcode-Integration.md
  Documentation/ConfigFile.md
  Documentation/Creating-your-templates.md
  Documentation/MigrationGuide.md
  Documentation/templates/MigrationGuide.md
  README.md
  Sources/SwiftGen/Commander/ConfigCommands.swift
  Sources/SwiftGen/Commander/ParserCLICommands.swift
  Sources/SwiftGen/Commander/TemplateCommands.swift
  Sources/SwiftGen/Commander/TemplatesCommands.swift
  Sources/SwiftGen/Config/Config.swift
  Sources/SwiftGen/TemplateRef.swift
  Sources/SwiftGen/main.swift
  SwiftGen.xcodeproj/project.pbxproj
  SwiftGen.xcodeproj/xcshareddata/xcschemes/swiftgen.xcscheme
  Tests/SwiftGenTests/ConfigLintTests.swift
  Tests/SwiftGenTests/ConfigReadTests.swift
Labels: status: ready to merge (waiting for CI), type: documentation, type: enhancement

#705 Migrate `swiftgen <parser>` command to `swiftgen run <parser>`
  CHANGELOG.md
  Documentation/Articles/Watch-a-folder-for-changes.md
  README.md
  Sources/SwiftGen/main.swift
  SwiftGen.playground/Pages/Colors-Demo.xcplaygroundpage/Contents.swift
  SwiftGen.playground/Pages/CoreData-Demo.xcplaygroundpage/Contents.swift
  SwiftGen.playground/Pages/Fonts-Demo.xcplaygroundpage/Contents.swift
  SwiftGen.playground/Pages/InterfaceBuilder-Demo.xcplaygroundpage/Contents.swift
  SwiftGen.playground/Pages/JSON-Demo.xcplaygroundpage/Contents.swift
  SwiftGen.playground/Pages/Plist-Demo.xcplaygroundpage/Contents.swift
  SwiftGen.playground/Pages/Strings-Demo.xcplaygroundpage/Contents.swift
  SwiftGen.playground/Pages/XCAssets-Demo.xcplaygroundpage/Contents.swift
  SwiftGen.playground/Pages/YAML-Demo.xcplaygroundpage/Contents.swift
Labels: status: ready to merge (waiting for CI), type: enhancement

#706 Better CLI error handling
  CHANGELOG.md
  Sources/SwiftGen/Commander/ConfigCommands.swift
  Sources/SwiftGen/main.swift
Labels: status: ready to merge (waiting for CI), type: bug/fix

#707 Setup scheme for profiling #trivial
  SwiftGen.xcodeproj/xcshareddata/xcschemes/swiftgen.xcscheme
Labels: status: ready to merge (waiting for CI), type: internal
